export default JSON.parse(JSON.stringify(
    [{
        "id": 1,
        "first_name": "Sammer",
        "last_name": "Sing",
        "gender": "Male",
        "manager_name": "Robort",
        "organisation": "Adams, Haley and Pacocha",
        "salary": 462453,
        "is_admin": true,
        "role": 1,
        "EmpNo":233,
        "username":"Sam",
        "password":"sam@123"
    
    },
    {
        "id": 2,
        "first_name": "preeti",
        "last_name": "Rao",
        "gender": "Female",
        "manager_name": "Elsa",
        "organisation": "Rolfson, Dibbert and McCullough",
        "salary": 154210,
        "is_admin": true,
        "role": 2,
        "EmpNo":273,
        "username":"Preeti",
        "password":"Preeti@123"
    },
    {
        "id": 3,
        "first_name": "Mary",
        "last_name": "Gorge",
        "gender": "Female",
        "manager_name": "Richerd",
        "organisation": "O'Hara, Becker and Johnson",
        "salary": 485924,
        "is_admin": true,
        "role":3,
        "EmpNo":733,
        "username":"Mary",
        "password":"Mary@123"
    },
    {
        "id": 4,
        "first_name": "Wiiliam",
        "last_name": "Gillam",
        "gender": "Male",
        "manager_name": "Jenny",
        "organisation": "Reilly-Bailey",
        "salary": 94051, 
        "is_admin": true,
        "role": 1,
        "EmpNo":456,
        "username":"Wiiliam",
        "password":"will@123"
    },
    {
        "id": 5,
        "first_name": "Raksesh",
        "last_name": "Kumar",
        "gender": "Female",
        "manager_name": "",
        "organisation": "Roberts Inc",
        "salary": 259548,
        "is_admin": false,
        "role": 2,
        "EmpNo":876,
        "username":"Rakesh4",
        "password":"Rakesh@123"
    },
    {
        "id": 6,
        "first_name": "Jenny",
        "last_name": "Lucifer",
        "gender": "Female",
        "manager_name": "Albert",
        "organisation": "Auer Group",
        "salary": 417289,
        "is_admin": true,
        "role": 3,
        "EmpNo":987,
        "username":"Jenny",
        "password":"Jenny@123"
    },
    {
        "id": 7,
        "first_name": "Geeta",
        "last_name": "kumari",
        "gender": "Female",
        "manager_name": "Krunal",
        "organisation": "Roob Group",
        "salary": 495806,
        "is_admin": false,
        "role": 3,
        "EmpNo":654,
        "username":"Geeta",
        "password":"Geeta@123"
    },
    {
        "id": 8,
        "first_name": "Gaurav",
        "last_name": "Sing",
        "gender": "Male",
        "manager_name": "Pritesh",
        "organisation": "Mayer, Batz and Cummings",
        "salary": 260909,
        "is_admin": true,
        "role": 3,
        "EmpNo":986,
        "username":"Gaurav",
        "password":"Gaurav@123"
    },
    {
        "id": 9,
        "first_name": "Rajesh",
        "last_name": "sinha",
        "gender": "Male",
        "manager_name": "Rohan",
        "organisation": "Rogahn-Okuneva",
        "salary": 414086,
        "is_admin": false,
        "role":2,
        "EmpNo":435,
        "username":"Raj",
        "password":"Raj@123"
    },
    ]
))